# Generated by Django 5.2.6 on 2025-10-24 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0005_propiedades_actualizado_en_propiedades_creado_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(max_length=255, upload_to='propiedades/%Y/%m/%d/')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255)),
                ('tipo_archivo', models.CharField(blank=True, max_length=50)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('es_principal', models.BooleanField(default=False)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='propiedades.propiedades')),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-es_principal', '-fecha_subida'],
            },
        ),
    ]
