# Generated by Django 5.2.6 on 2025-10-13 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0003_alter_reservas_options_reservas_actualizado_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('reserva_creada', 'Nueva Reserva'), ('reserva_confirmada', 'Reserva Confirmada'), ('reserva_cancelada', 'Reserva Cancelada'), ('recordatorio_reserva', 'Recordatorio de Reserva'), ('recordatorio_checkin', 'Recordatorio de Check-in'), ('recordatorio_checkout', 'Recordatorio de Check-out'), ('recordatorio_resena', 'Recordatorio de Reseña'), ('pago_recibido', 'Pago Recibido'), ('pago_fallido', 'Pago Fallido'), ('sistema', 'Mensaje del Sistema')], max_length=50)),
                ('leida', models.BooleanField(default=False)),
                ('enviada', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservas.reservas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
