# Generated by Django 5.2.6 on 2025-10-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('reserva_creada', 'Nueva Reserva'), ('reserva_confirmada', 'Reserva Confirmada'), ('reserva_aceptada', 'Reserva Aceptada'), ('reserva_cancelada', 'Reserva Cancelada'), ('reserva_rechazada', 'Reserva Rechazada'), ('reserva_completada', 'Reserva Completada'), ('recordatorio_checkin', 'Recordatorio de Check-in'), ('recordatorio_checkout', 'Recordatorio de Check-out'), ('recordatorio_resena', 'Recordatorio de Reseña'), ('pago_recibido', 'Pago Recibido'), ('pago_fallido', 'Pago Fallido'), ('pago_reembolsado', 'Pago Reembolsado'), ('sistema', 'Mensaje del Sistema')], max_length=50),
        ),
    ]
