# Generated by Django 5.2.7 on 2025-12-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_reporte', models.CharField(choices=[('reservas', 'Reservas'), ('propiedades', 'Propiedades'), ('usuarios', 'Usuarios'), ('ingresos', 'Ingresos'), ('facturas', 'Facturas'), ('ocupacion', 'Ocupación'), ('personalizado', 'Personalizado')], max_length=20)),
                ('configuracion', models.JSONField(default=dict, help_text='Configuración del reporte: campos seleccionados, filtros, etc.')),
                ('es_publico', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_guardados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Guardado',
                'verbose_name_plural': 'Reportes Guardados',
                'db_table': 'reportes_guardados',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=20)),
                ('configuracion_usada', models.JSONField(default=dict)),
                ('parametros_filtro', models.JSONField(default=dict)),
                ('prompt_ia', models.TextField(blank=True, help_text='Prompt usado si fue generado por IA')),
                ('respuesta_ia', models.TextField(blank=True, help_text='Respuesta de IA si aplica')),
                ('resultado_resumen', models.JSONField(default=dict, help_text='Resumen de los resultados')),
                ('formato_exportado', models.CharField(choices=[('json', 'JSON'), ('pdf', 'PDF'), ('csv', 'CSV'), ('excel', 'Excel')], default='json', max_length=10)),
                ('tiempo_generacion', models.FloatField(default=0, help_text='Tiempo en segundos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reporte_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generaciones', to='reportes.reporteguardado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'db_table': 'reportes_generados',
                'ordering': ['-creado_en'],
            },
        ),
    ]
