# Generated by Django 5.2.7 on 2025-11-25 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0005_reservas_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('aprobado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.reservas')),
            ],
        ),
    ]
