# Generated by Django 5.2.6 on 2025-10-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
