# Generated by Django 5.2.7 on 2025-11-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_customuser_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='N_Cel',
            field=models.CharField(blank=True, default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='correo',
            field=models.EmailField(blank=True, default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
