# Generated by Django 5.2.6 on 2025-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=14)),
                ('descripcion', models.CharField(max_length=120)),
                ('fecha_Creacion', models.DateField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
