# Generated by Django 5.2.7 on 2025-11-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicidad',
            options={'ordering': ['-creado_en']},
        ),
    ]
