# Generated by Django 5.2.6 on 2025-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('permisos', models.ManyToManyField(related_name='roles', to='permisos.permisos')),
            ],
        ),
    ]
