# Generated by Django 5.2.6 on 2025-09-23 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cant_huesp', models.PositiveIntegerField()),
                ('cant_noches', models.PositiveIntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comentario_huesp', models.CharField(max_length=120)),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('status', models.BooleanField(null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propiedades.propiedades')),
            ],
        ),
    ]
