# Generated by Django 5.2.6 on 2025-10-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reservas_options_reservas_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
