# Generated by Django 5.2.7 on 2025-11-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reservas_status'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='reservas', to='servicios.servicio'),
        ),
    ]
