# Generated by Django 5.2.6 on 2025-09-23 04:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=datetime.date.today)),
                ('duracion', models.CharField(choices=[('Mensual', 'Mensual'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=10)),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='suscripciones.suscripciones')),
            ],
        ),
    ]
