# Generated by Django 5.2.6 on 2025-09-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.TextField(max_length=200)),
                ('direccion', models.TextField(max_length=50)),
                ('tipo', models.CharField(blank=True, choices=[('Departamento', 'Departamento'), ('Casa', 'Casa')], default=' ')),
                ('serv', models.CharField(blank=True, choices=[('Agua', 'Agua'), ('Luz', 'Luz'), ('Gas', 'Gas'), ('Pavimento', 'Pavimento'), ('Internet', 'Internet'), ('Aire', 'Aire')], default=' ')),
                ('status', models.BooleanField()),
                ('precio_noche', models.FloatField(default=0)),
                ('cant_bath', models.IntegerField(default=0)),
                ('cant_hab', models.IntegerField(default=0)),
            ],
        ),
    ]
