# Generated by Django 5.2.6 on 2025-10-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedades',
            name='serv',
        ),
        migrations.AddField(
            model_name='propiedades',
            name='descuento',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='servicios_basicos',
            field=models.JSONField(default=list),
        ),
    ]
