# Generated by Django 5.2.6 on 2025-10-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_remove_propiedades_serv_propiedades_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='tipo',
            field=models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa')], default='Casa', max_length=20),
        ),
    ]
