# Generated by Django 5.2.6 on 2025-10-18 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0004_alter_propiedades_status_alter_propiedades_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propiedades',
            name='estado_baja',
            field=models.CharField(choices=[('activa', 'Activa'), ('baja_temporal', 'Baja Temporal'), ('baja_indefinida', 'Baja Indefinida')], default='activa', max_length=20),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='fecha_baja_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='fecha_baja_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='max_huespedes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='motivo_baja',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='pets',
            field=models.BooleanField(default=False),
        ),
    ]
