# Generated by Django 5.2.7 on 2025-10-30 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_propiedades_actualizado_en_propiedades_creado_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedades',
            name='servicios_basicos',
        ),
        migrations.AddField(
            model_name='propiedades',
            name='caracteristicas',
            field=models.JSONField(default=list, help_text='Lista de características de la propiedad'),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='ciudad',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='direccion_completa',
            field=models.TextField(blank=True, help_text='Dirección completa formateada', max_length=200),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='es_destino_turistico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud de la propiedad', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud de la propiedad', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='pais',
            field=models.CharField(default='Bolivia', max_length=50),
        ),
        migrations.AddField(
            model_name='propiedades',
            name='provincia',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='tipo',
            field=models.CharField(choices=[('Departamento', 'Departamento'), ('Casa', 'Casa'), ('Cabaña', 'Cabaña')], default='Casa', max_length=20),
        ),
    ]
