# Generated by Django 5.2.7 on 2025-10-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0006_remove_propiedades_servicios_basicos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='departamento',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
