# Generated by Django 5.2.7 on 2025-11-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0007_propiedades_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedades',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='direccion_completa',
            field=models.TextField(help_text='Dirección completa formateada', max_length=200),
        ),
    ]
