# Generated by Django 5.2.7 on 2025-11-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0008_remove_propiedades_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedades',
            name='latitud',
            field=models.FloatField(blank=True, help_text='Latitud de la propiedad', null=True),
        ),
        migrations.AlterField(
            model_name='propiedades',
            name='longitud',
            field=models.FloatField(blank=True, help_text='Longitud de la propiedad', null=True),
        ),
    ]
