# Generated by Django 5.2.6 on 2025-09-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscripciones',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
