# Generated by Django 5.2.6 on 2025-10-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_suscripciones_duracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscripciones',
            name='duracion',
        ),
    ]
