# Generated by Django 5.2.7 on 2025-11-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0004_remove_suscripciones_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripciones',
            name='duracion',
            field=models.CharField(choices=[('Mensual', 'Mensual'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensual', max_length=10),
        ),
    ]
