# Generated by Django 5.2.7 on 2025-11-25 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisos',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
